name: vitamin
favicon: null
layout_spectrum: 0.09582
typography_spectrum: 0.09485072479583323
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#240d13'
    - '#fe8a8b'
    - '#8fcedf'
    - '#00609a'
  brandStrength: 0.6875
  lightness: 0.7756933856289834
  saturation: 0.16532450448721647
  rhythmicContrast: 0.5756706085521728
purpose: []
