name: vitamin
favicon: null
layout_spectrum: 0.09582
typography_spectrum: 0.75369
title: Vitamin on Da Grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#240d13'
    - '#fe8a8b'
    - '#8fcedf'
    - '#00609a'
  brandStrength: 0.25
  lightness: 0.1875
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
