name: vitamin
favicon: null
layout_spectrum: 0.40351
typography_spectrum: 0.74837
title: Vitamin on Da Grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#fefefe'
    - '#71505b'
    - '#00d4ea'
    - '#be9778'
  brandStrength: 1
  lightness: 0.125
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
